#R handles complex computations using:

# # Vector – A basic data structure of R containing the same type of data
# # Matrices – A matrix is a rectangular array of numbers 
# or other mathematical objects. We can do operations such as
# addition and multiplication on Matrix in R.
# # Lists – Lists store collections of objects when vectors 
# are of same type and length in a matrix.
# # Data Frames – Generated by combining together 
# multiple vectors such that each vector becomes a separate column.


###start

5
5+3
x = 5
y = 6
x*y
x/y
y = "A"
class(x)
class(y)


#printing 
print(x)

print("Humay Hasilli")
'Humay Hasilli'
a = 'Humay Hasilli'

print(paste("Salam, yasim ", x ))

print(paste('Salam , adim -  ' , a))

toupper(a)
tolower(a)

##Vektorlar c()
?c()
c(1,2,3,4,5)

y = c(1,2,3,4,5)



class(y)

y
z <- c(10,20,30,40)
t <-  c("A" , "B" , "C")

class(t)


#AVTOMATIK STRING OLARAQ TANIYIR
e <-  c("A" , "B" , 1 , 2)
e
Y <-  c(1,2,4,6,8)
Y
# Vektorlarda stringler ve numeric deyerler ic ice ola bilmir


## LIstler indexlere gore  netice cixarir, ic ice la biler, icine vektor
# elave ede bilinir.Ic ice vektorlar yarada bilerem, obslari adlandirmaq mumkudnur


l1 <-  list(13, 45 , 64,3)

l2 <-  list('a' , 'c' )
l2

l3 <-  list(1,2,'a') # Muxtelif tipleri icinde saxlayir
l3


#list icinde vektor 

l4 <-  list(c(1,2,3,4,5) , "A" ,  5)
l4


#Indexlene bilir listler


l5 <-  list('a' = c(1,2,3,4,5) , "b" =  "a")
l5

l5$a

l5$b

## DataFrame setir ve sutunlar tipinde olan data
# eslinde her bir deyishken (sutun) ayrica bir vektordur

x <-  c(10,20,30,40)
y <-  c("a" , "c" , "D" ,"e")
z <-  c(11,22,31,22)

#data.frame()

data.frame(x,y,z)

df <-  data.frame(x,y,z)
df


## setir saylari bir birine beraber olmalidir
View(df)
summary(df)



df

# sutun adlarin deyishek

df2 <-  data.frame("Avar" = x , "BVar" = y , "Cvar" = z)
df2



df4 <-  data.frame('a' = c(1,2,4,5) ,
                       'b' = c(34,35,36,38) ,
                       'c' = c(89,90,78,44))
df4



##Matrisler 
# dataframelerin bir kopyasi kimidir. Riyazi ishler gorulur uzerinde
#Sutun basliqlari yoxdur, setir ve sutun nomreleri vardir
# matrix()

x = c(1,2,3,4)
matrix(x , nrow = 2, ncol = 2)

mat = matrix(x , nrow = 2, ncol = 2 , byrow = TRUE)

mat + 2

as.data.frame(mat)

## Vektorlarda observation secimi 

x <-  c(12,13,14,15,16)
x <- c('A' , 'B' , 'C')

# Birinci obs sec
x[1]

# İkinci obs Seçimi
x[2]

y <- c(1,2,3,4,5,6,7,8,9,10)

#### 1 ve 3 arasındaki obslar
y[1:3]
y[4:9]
y[5:8]


y[c(5,6,7,8)]

t <- c(11,12,13,29,25,29,30,31,32)
t[c(4,8,9)]
t[c(4,8,15)]

t[c(1 , 2, 3)]
t[3:8]


# obs cixartmaq
x <- c(12,13,14,15,16)
x 
x[-1]
x[-5]

# Cixartmani qalici etmek ucun beraberlesdir

x = x[-1]
x = x[-4]
x
rm(x)
x <- c(12,13,14,15,16)

y <- x[-1]
y
x[c(1,2,3)]
x[c(-1,-2,-3)]

cixart <- c(2,3,1)
x[-cixart]

c <- x[-cixart]
c

x[-1:3] # xetali
x[-c(1:3)]

## obs deyisdirme
x <- c(10,11,21,32,43,56)

x[2] <- 33
x

x[c(1,2)] <- 1 
x

x[c(1,2)] <- c(10,11)
x

x <- c(11,22,33,44)

# 5-ci indexe obs elave et
x[5] <- 55
x
x[5:10] <- 3

x
x[12] <- 5

x[11] <- 1
x

x[c(13,14)] <- c(11,12)
x

###Listlerde observation sec

list(1,2,3,4)
list(c(1,2,3) , 'A' , 10)


x <- list(11,12 , c('A' , 'B' , 'C') )

x
x[1]

y <- list('A' = c(1,2,3,4) , 'B' = c(11,22,33,44))
names(y)

#secimler

y$B
y["B"]



#LIstde obs silmek

x <- list(1,2,3 , c(11,22,33))
x

x[1] <- NULL
x

y <- list(c(1,2,3) , 'A' , 'B')
y
y[1] <- NULL

y



y <- list('A' = c(1,2,3) , 'B' = 2)

y$A <- NULL
y

##Obs deyishmek 
x <- list(1,2,3,4)
#silir
x <- x[-2] 
x

x <- list('A' , 'B' , 'C' , 12 , 13, c(11,22,33,44))

x[[2]] <- 'DD' 
x[1] <- 'AA'

x[[6]][4] <- 0
x

x <- list(11,12,13)
x[[2]] <- 15
x

# YEni obs elave et
x
x[4] <- 33
x

x[5] <- 34
x

x[[6]] <- 35
x

x[[7]] <- c(11,12,13,14)
x

x[8] <- c(11,12,13,14)
x

x[[15]] <- 15
x
x
#uzunluqu verir 
length(x)



##RIyazi emeller

x <- 5
y <- 15 

# chixma
y - x 

# Bölme 
y / x

# vurma işlemi
y * x

# Y'nin kvadrati
y**2

# Y'nin kubu
y**3


# 12'nin kvadrati 
z = 12**2
z

# kokalma
sqrt(z)

t = -3*6
t

t**3
t/2

#Vektorlarda
x1 <- c(13,24,35,56)
x2 <- c(12,23)

x1 + x2
x1 * x2



# Vektor uzunluq

x1 <- c(11,22,33,44,55,66,67,56,5,6,5,4,34)
length(x1)

x2 <- c('A' ,'B' ,'C' ,'D',
        'A' ,'B' ,'C' ,'D',
        'A' ,'B' ,'C' ,'D',
        'A' ,'B' ,'C' ,'D',
        'A' ,'B' ,'C' ,'D',
        'A' ,'B' ,'C' ,'D',
        'A' ,'B' ,'C' ,'D',
        'A' ,'B' ,'C' ,'D',
        'A' ,'B' ,'C' ,'D',
        'A' ,'B' ,'C' ,'D'
)

# Vektor uzunluğu
length(x2)
x2[40]

x2[length(x2)]

len <- length(x2)
len




x <- c(12,34,23,11,4,5,78)

# Minimum deyer 
min(x)

# Maximum deyer
max(x)

min(x) + max(x)

4==5
5==5
x <- c(12,34,56,45,78,54)
x== 34
x < 12
which(x< 56)
x[which(x< 56)]

#sequence
1:23
seq(10)
seq(1,10)
x <- seq(-4 , 5)
x

seq(from = 0 , to = 10 , by = 3)

df <- data.frame( 'A' = c(1,2,3,4,5) , 'B' = c(34,35,35,34,12))
df

df <- df[-3 , ]
df

uzunluq <- length(df$A)
uzunluq

row.names(df)

row.names(df) <- seq(from = 1 , to = uzunluq)
df

#Sampling
x <- seq(from = 100 , to = 300 , by = 10)
x

sample(x , size = 3)
y = sample(x , size = 5)
y


##Tekrar eden deyerleri yarat
rep(4 , 14)

#Siralama
x <- c(12,34,12,4,5,45,22,67,34)




sort(x)
sort(x , decreasing = T)
?sort()

#Temel statistika
# ORtalama
mean(x)
sd(x)
# VArians
var(x)
median(x)

quantile(x,0.25)
?quantile
quantile(x,0.75)


#frekans - tezlik
x <- c(12,12,13,13,14,14,13,12,12,15,15,16)
length(x) 

unique(x)


table(x)
x <- c(12,13,14,15,NA)

sum(x)
sum(x , na.rm = T)


skew(x)

















##Matris yarat

m <- matrix(c(11,12,13,14) , nrow = 2 , ncol=2 , byrow = TRUE)
m

m1 <- matrix(c(12,22,34,45,45,56,57,68) , nrow=2 , ncol=4 , byrow=TRUE)

m1
m1[1,1]
m1[2,4]

# Matrisin parçalarını seçmek


m1[1:2,2:4]
m1[c(1) , c(1,3,4)]

m <- matrix(c(1,2,3,4) , nrow=2 , ncol=2 , byrow=T)
m
class(m[,-2])
class(m)

m <- m[,-2]
m
class(m)
as.matrix(m)

m1 <- matrix(c(11,22,33,44,55,66,77,88) , 4, 2 , T)
m1

# 1 setir cixartmaq
m1
m1[-3 , ]

# Chox setir cixartmaq
m1[-c(2,3) , -3]
m1[-c(2:3) , ]
m1[-c(2:4) , ]


# deyerleri NA Cevir
m1
m1[2,2] <- NA
m1
m1[c(1,2) , 1] <- NA
m1

m1[2,2] <- 123
m1

m2 <- m1[-4,]
m2

# Dataframelerde obs sec
df <- data.frame('A' = c(12,13,14,15,16) , 'B' = c('A' , 'B' , 'C' , 'D' , 'E'))
df
df[1,1]
df[1,2]

df[,2]
df[,1]
df[5,]

df2 <- data.frame( 'A' = c(12,13,14,15,16) , 
                   'B' = c('A' , 'B' , 'C' , 'D' , 'E'),
                   'C' = c(45,23,67,89,24))

df2

df2[,c(2,3)]
class(df2[,c(2,3)])

df2[2]
df2[1]
class(df2[1])

df2[['A']]
df2[,1]


df2
df2[1]
df2$A # vektor
df2$B
df2$C

df2[c('A' , 'B')]



df <- data.frame('A' = c(1,2,3,4,5) , 'B' = c(4,5,6,7,8))
df

# ikinci sutunun cixarilmis secimi
df[-2]
df[-1]

df[2]
# qalici olaraq cixArt
df <- df[-2]
df

df <- data.frame('A' = c(1,2,3,4,5) , 'B' = c(4,5,6,7,8))

df[,1]
df[,-1]

df[-1]

df[2] <- NULL
df

df <- data.frame('A' = c(1,2,3,4,5) , 'B' = c(4,5,6,7,8))
df
df['A'] <- NULL
df

df <- data.frame('A' = c(1,2,3,4,5) , 
                 'B' = c(4,5,6,7,8),
                 'C' = c(11,222,32,41,54))

df[-c(1,3)]
df[,-c(1,3)] # neticesi vektordur
df[,-3] # Bu DF-dir

df[c('A' ,'B')] <- NULL
df


df <- data.frame('A' = c(1,2,3,4,5) , 
                 'B' = c(4,5,6,7,8),
                 'C' = c(11,222,32,41,54))

df <- df[-1,]
df
df[1,]

df[-c(2:4) ,]
df[-c(1,4),]

df <- data.frame('A' = c(1,2,3,4) , 
                 'B' = c('A' , 'B' , 'C' , 'D'),
                 'C' = c(11,22,33,44))


cbind(df , 'D' = c(33,44,55,66))
df
df <- cbind(df , 'D' = c(33,44,55,66))
df

df[5] <- c(12,13,14,15)
df
df$Yeni <- c('F' , 'G' , 'H' , 'Z')
df

df['Yeni2'] <- c(1,2,3,4)
df

# YEni setir elave et

df[5 , ] <- c(1,2,3,4,5,6 , 7)
df
df[6 , ] <- c(1,'A',3,4,5,6 , 7)
df

df[5,2] <- 'T'
df

df[7 , ] <- c(1,'C',3,4,5,6 , 7)
df
df[5,2] <- 'A'
df
class(df$Yeni)

df
rbind(df , data.frame('A' = c(1) , 'B' = c('C') , 
                      'C' = c(23) , 'D' = c(13) , 'V5' = c(23),
                      'Yeni'= c('F') , 'Yeni2' = c(13) ))

rbind(df , data.frame('A' = c(1 ,2) , 'B' = c('C' ,'A') , 
                      'C' = c(23 ,24) , 'D' = c(13 ,14) , 'V5' = c(23 , 24),
                      'Yeni'= c('F' ,'A') , 'Yeni2' = c(13 , 14) ))

elave <- data.frame('A' = c(1 ,2) , 'B' = c('C' ,'A') , 
                        'C' = c(23 ,24) , 'D' = c(13 ,14) , 'V5' = c(23 , 24),
                        'Yeni'= c('F' ,'A') , 'Yeni2' = c(13 , 14) )

elave

rbind(df , elave)

elave <- data.frame('A' = c(1 ,2) , 'B' = c('C' ,'T') , 
                        'C' = c(23 ,24) , 'D' = c(13 ,14) , 'V5' = c(23 , 24),
                        'Yeni'= c('F' ,'A') , 'Yeni2' = c(13 , 14) )

df <- rbind(df , elave)


elaveSutun <- data.frame('J' = c(1,2,3,4,5,6,7,8,9) , 'E' = c(1,2,3,4,5,6,7,8,9))
elaveSutun

cbind(df , elaveSutun)

